CREATE TABLE `users` (

    `id` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL
    
) ENGINE=INNODB DEFAULT CHARSET=utf8;